name: '$(Build.SourceBranchName)$(System.PullRequest.SourceBranch)$(Rev:.r)'

trigger:
  - main
  - feature/*
  - release/*

pr:
  - main
  - releases/*

parameters:
  - name: prDeployment
    type: boolean
    default: true
  - name: branchDeployment
    type: boolean
    default: true
  - name: sndDeployment
    type: boolean
    default: true

resources:
  repositories:
    - repository: templates
      endpoint: DEFRA
      type: github
      name: defra/fcp-pipeline-common
      # ref: branch-name

extends:
  template: fcp-common-pipeline.yaml@templates
  parameters:
    appFrameworkType: nodejs
    prDeployment: ${{ parameters.prDeployment }}
    branchDeployment: ${{ parameters.branchDeployment }}
    sndDeployment: ${{ parameters.sndDeployment }}
    variableGroupName: ffc-doc-statement-constructor-env-var
    failOnThreshold: moderate  # Optional: moderate (default), low, high, critical
    pr_params:
      container.endpointEnabled: $(pr_endpointEnabled)
      container.pollWindowEnabled: $(pr_pollWindowEnabled)
      container.sfi23QuarterlyStatementProcessingActive: $(pr_sfi23QuarterlyStatementProcessingActive)
      container.delinkedStatementProcessingActive: $(pr_delinkedStatementProcessingActive)
    snd2_params:
      container.endpointEnabled: $(snd2_endpointEnabled)
      container.pollWindowEnabled: $(snd2_pollWindowEnabled)
      container.sfi23QuarterlyStatementProcessingActive: $(snd2_sfi23QuarterlyStatementProcessingActive)
      container.delinkedStatementProcessingActive: $(snd2_delinkedStatementProcessingActive)
    dev_params:
      container.endpointEnabled: $(dev_endpointEnabled)
      container.pollWindowEnabled: $(dev_pollWindowEnabled)
      container.sfi23QuarterlyStatementProcessingActive: $(dev_sfi23QuarterlyStatementProcessingActive)
      container.delinkedStatementProcessingActive: $(dev_delinkedStatementProcessingActive)
    test_params:
      container.endpointEnabled: $(test_endpointEnabled)
      container.pollWindowEnabled: $(test_pollWindowEnabled)
      container.sfi23QuarterlyStatementProcessingActive: $(test_sfi23QuarterlyStatementProcessingActive)
      container.delinkedStatementProcessingActive: $(test_delinkedStatementProcessingActive)
    pre_params:
      container.endpointEnabled: $(pre_endpointEnabled)
      container.pollWindowEnabled: $(pre_pollWindowEnabled)
      container.sfi23QuarterlyStatementProcessingActive: $(pre_sfi23QuarterlyStatementProcessingActive)
      container.delinkedStatementProcessingActive: $(pre_delinkedStatementProcessingActive)
    prd_params:
      container.endpointEnabled: $(prd_endpointEnabled)
      container.pollWindowEnabled: $(prd_pollWindowEnabled)
      container.sfi23QuarterlyStatementProcessingActive: $(prd_sfi23QuarterlyStatementProcessingActive)
      container.delinkedStatementProcessingActive: $(prd_delinkedStatementProcessingActive)
