services:
  ffc-doc-statement-constructor:
    build:
      context: .
      target: production
    image: ffc-doc-statement-constructor
    container_name: ffc-doc-statement-constructor
    depends_on:
      - ffc-doc-statement-constructor-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-doc-statement-constructor-local
      APPLICATIONINSIGHTS_CONNECTION_STRING): ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      DATA_TOPIC_ADDRESS: ${DATA_TOPIC_ADDRESS:-ffc-doc-statement-data}${MESSAGE_QUEUE_SUFFIX}
      DATA_SUBSCRIPTION_ADDRESS: ${DATA_SUBSCRIPTION_ADDRESS:-ffc-doc-statement-constructor}${MESSAGE_QUEUE_SUFFIX}
      ALERT_TOPIC_ADDRESS: ${ALERT_TOPIC_ADDRESS:-ffc-doc-alerting}${MESSAGE_QUEUE_SUFFIX}
      STATEMENT_TOPIC_ADDRESS: ${STATEMENT_TOPIC_ADDRESS:-ffc-doc-statements}${MESSAGE_QUEUE_SUFFIX}
      DATA_PROCESSING_ERROR: ${DATA_PROCESSING_ERROR:-ffc-doc-alerting}${MESSAGE_QUEUE_SUFFIX}
      ALERTING_TOPIC_ADDRESS: ${ALERTING_TOPIC_ADDRESS:-ffc-doc-alert}${MESSAGE_QUEUE_SUFFIX}
      POSTGRES_DB: ffc_doc_statement_constructor
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-doc-statement-constructor-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      MAX_PROCESSING_REQUEST_AGE_HOURS: ${MAX_PROCESSING_REQUEST_AGE_HOURS}

  ffc-doc-statement-constructor-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_doc_statement_constructor
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
