{{- include "ffc-helm-library.container-secret" (list . "ffc-doc-statement-constructor.container-secret") -}}
{{- define "ffc-doc-statement-constructor.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPLICATIONINSIGHTS_CONNECTION_STRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  POSTGRES_USERNAME: {{ .Values.postgresService.postgresUser | quote }}
{{- end -}}
