{{- include "ffc-helm-library.deployment" (list . "ffc-doc-statement-constructor.deployment") -}}
{{- define "ffc-doc-statement-constructor.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-doc-statement-constructor.container") }}
{{- end -}}
