---
environment: production
environmentCode: dev
container:
  azureStorageAccountName: devffcdocst1001
  messageQueueHost: DEVFFCINFSB1001.servicebus.windows.net
  redisHostname: DEVFFCINFRD1001.redis.cache.windows.net
ingress:
  server: azure.defra.cloud
  endpoint: ffc-doc-statement-constructor-dev
secretProviderClass:
  azure:
    keyvaultName: DEVFFCINFKV1001
    objects:
      - objectName: devtest-ffcahwr-appInsights-connectionString
        objectType: secret
      - objectName: dev-postgresUser
        objectType: secret

  secretObjects:
    - secretName: ffc-doc-statement-constructor
      type: Opaque
      data:
        - objectName: devtest-ffcahwr-appInsights-connectionString
          key: APPLICATIONINSIGHTS_CONNECTION_STRING
        - objectName: dev-postgresUser
          key: POSTGRES_USERNAME