---
environment: production
environmentCode: prd
container:
  messageQueueHost: PRDFFCINFSB1001.servicebus.windows.net
  azureStorageAccountName: prdffcdocst1001
  redisHostname: PRDFFCINFRD1001.redis.cache.windows.net
secretProviderClass:
  azure:
    keyvaultName: PRDFFCINFKV1001
    objects:
      - objectName: prd-ffcahwr-appinsights-connectionString
        objectType: secret

  secretObjects:
    - secretName: ffc-doc-statement-constructor
      type: Opaque
      data:
        - objectName: prd-ffcahwr-appinsights-connectionString
          key: APPLICATIONINSIGHTS_CONNECTION_STRING
notifyApiKeySecret: secret_api_key-822638a6-2c67-44ef-9fe0-98tc9bb99272-45yne8e4-7daa-4324-89f3-7e53x7bqe3l9